"""Projects

Revision ID: 0bef3cf05488
Revises: 3051f562ca5d
Create Date: 2026-03-06 00:40:05.926631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bef3cf05488'
down_revision: Union[str, Sequence[str], None] = '3051f562ca5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('patch_detectors', 'action',
    #            existing_type=sa.VARCHAR(length=200),
    #            type_=sa.JSON(),
    #            existing_nullable=True)

    op.drop_column('patch_detectors', 'action')
    op.add_column('patch_detectors', sa.Column('actions', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('patch_detectors', 'action',
    #            existing_type=sa.JSON(),
    #            type_=sa.VARCHAR(length=200),
    #            existing_nullable=True)
    op.drop_column('patch_detectors', 'actions')
    op.add_column('patch_detectors', sa.Column('action', sa.VARCHAR(length=200), nullable=True))
    # ### end Alembic commands ###
