"""Project

Revision ID: 3051f562ca5d
Revises: 06da265a750a
Create Date: 2026-03-05 12:16:00.774365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3051f562ca5d'
down_revision: Union[str, Sequence[str], None] = '06da265a750a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_id'), 'clients', ['id'], unique=False)
    op.create_index(op.f('ix_clients_name'), 'clients', ['name'], unique=True)
    op.create_table('environments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('env_type', sa.String(length=50), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_environments_id'), 'environments', ['id'], unique=False)
    op.add_column('patch_detectors', sa.Column('server_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_patch_detectors_server_id'), 'patch_detectors', ['server_id'], unique=False)
    op.create_foreign_key(None, 'patch_detectors', 'servers', ['server_id'], ['id'], ondelete='CASCADE')
    op.add_column('patch_executions', sa.Column('server_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_patch_executions_server_id'), 'patch_executions', ['server_id'], unique=False)
    op.create_foreign_key(None, 'patch_executions', 'servers', ['server_id'], ['id'], ondelete='CASCADE')
    op.add_column('patchs', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('patchs', sa.Column('patch_type', sa.String(length=50), nullable=False))
    op.add_column('patchs', sa.Column('component', sa.String(length=50), nullable=False))
    op.add_column('patchs', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('patchs', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('patchs', sa.Column('client_id', sa.Integer(), nullable=True))
    op.add_column('patchs', sa.Column('environment_id', sa.Integer(), nullable=True))
    op.add_column('patchs', sa.Column('server_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('patchs_uploaded_by_fkey'), 'patchs', type_='foreignkey')
    op.create_foreign_key(None, 'patchs', 'servers', ['server_id'], ['id'])
    op.create_foreign_key(None, 'patchs', 'environments', ['environment_id'], ['id'])
    op.create_foreign_key(None, 'patchs', 'clients', ['client_id'], ['id'])
    op.create_foreign_key(None, 'patchs', 'users', ['user_id'], ['id'])
    op.drop_column('patchs', 'uploaded_by')
    op.add_column('prepatchs', sa.Column('server_id', sa.Integer(), nullable=True))
    op.add_column('prepatchs', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_prepatchs_server_id'), 'prepatchs', ['server_id'], unique=False)
    op.create_foreign_key(None, 'prepatchs', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'prepatchs', 'servers', ['server_id'], ['id'], ondelete='CASCADE')
    op.add_column('servers', sa.Column('client_id', sa.Integer(), nullable=True))
    op.add_column('servers', sa.Column('environment_id', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_servers_detector_id'), table_name='servers')
    op.drop_index(op.f('ix_servers_environment'), table_name='servers')
    op.drop_index(op.f('ix_servers_executions_id'), table_name='servers')
    op.drop_index(op.f('ix_servers_prepatch_id'), table_name='servers')
    op.drop_constraint(op.f('servers_executions_id_fkey'), 'servers', type_='foreignkey')
    op.drop_constraint(op.f('servers_prepatch_id_fkey'), 'servers', type_='foreignkey')
    op.drop_constraint(op.f('servers_detector_id_fkey'), 'servers', type_='foreignkey')
    op.create_foreign_key(None, 'servers', 'clients', ['client_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'servers', 'environments', ['environment_id'], ['id'], ondelete='SET NULL')
    op.drop_column('servers', 'detector_id')
    op.drop_column('servers', 'environment')
    op.drop_column('servers', 'executions_id')
    op.drop_column('servers', 'prepatch_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servers', sa.Column('prepatch_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('servers', sa.Column('executions_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('servers', sa.Column('environment', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('servers', sa.Column('detector_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'servers', type_='foreignkey')
    op.drop_constraint(None, 'servers', type_='foreignkey')
    op.create_foreign_key(op.f('servers_detector_id_fkey'), 'servers', 'patch_detectors', ['detector_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('servers_prepatch_id_fkey'), 'servers', 'prepatchs', ['prepatch_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('servers_executions_id_fkey'), 'servers', 'patch_executions', ['executions_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_servers_prepatch_id'), 'servers', ['prepatch_id'], unique=False)
    op.create_index(op.f('ix_servers_executions_id'), 'servers', ['executions_id'], unique=False)
    op.create_index(op.f('ix_servers_environment'), 'servers', ['environment'], unique=False)
    op.create_index(op.f('ix_servers_detector_id'), 'servers', ['detector_id'], unique=False)
    op.drop_column('servers', 'environment_id')
    op.drop_column('servers', 'client_id')
    op.drop_constraint(None, 'prepatchs', type_='foreignkey')
    op.drop_constraint(None, 'prepatchs', type_='foreignkey')
    op.drop_index(op.f('ix_prepatchs_server_id'), table_name='prepatchs')
    op.drop_column('prepatchs', 'user_id')
    op.drop_column('prepatchs', 'server_id')
    op.add_column('patchs', sa.Column('uploaded_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'patchs', type_='foreignkey')
    op.drop_constraint(None, 'patchs', type_='foreignkey')
    op.drop_constraint(None, 'patchs', type_='foreignkey')
    op.drop_constraint(None, 'patchs', type_='foreignkey')
    op.create_foreign_key(op.f('patchs_uploaded_by_fkey'), 'patchs', 'users', ['uploaded_by'], ['id'])
    op.drop_column('patchs', 'server_id')
    op.drop_column('patchs', 'environment_id')
    op.drop_column('patchs', 'client_id')
    op.drop_column('patchs', 'user_id')
    op.drop_column('patchs', 'created_at')
    op.drop_column('patchs', 'component')
    op.drop_column('patchs', 'patch_type')
    op.drop_column('patchs', 'description')
    op.drop_constraint(None, 'patch_executions', type_='foreignkey')
    op.drop_index(op.f('ix_patch_executions_server_id'), table_name='patch_executions')
    op.drop_column('patch_executions', 'server_id')
    op.drop_constraint(None, 'patch_detectors', type_='foreignkey')
    op.drop_index(op.f('ix_patch_detectors_server_id'), table_name='patch_detectors')
    op.drop_column('patch_detectors', 'server_id')
    op.drop_index(op.f('ix_environments_id'), table_name='environments')
    op.drop_table('environments')
    op.drop_index(op.f('ix_clients_name'), table_name='clients')
    op.drop_index(op.f('ix_clients_id'), table_name='clients')
    op.drop_table('clients')
    # ### end Alembic commands ###
