"""ChangeActions

Revision ID: d0fa21546d67
Revises: 0bef3cf05488
Create Date: 2026-03-06 09:21:04.938529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd0fa21546d67'
down_revision: Union[str, Sequence[str], None] = '0bef3cf05488'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patch_detectors', 'actions')
    op.add_column('patch_detectors', sa.Column('actions', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('patch_detectors', 'actions',
               existing_type=sa.String(length=500),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    # ### end Alembic commands ###
